#!/bin/bash
set -eux

PROJECT_NAME=$(basename $GITHUB_REPOSITORY)
ARCH=${GOARCH}
if [ $GOOS == 'darwin' ]; then
  ARCH="universal"
fi
NAME="${PROJECT_NAME}_${VERSION}_${GOOS}_${ARCH}"

EXT=''

if [ $GOOS == 'windows' ]; then
  EXT='.exe'
fi

tar cvfz ${NAME}.tar.gz "${PROJECT_NAME}${EXT}" LICENSE
shasum -a 256 ${NAME}.tar.gz | cut -d ' ' -f 1 > ${NAME}_sha256_checksum.txt
