#!/bin/bash
set -e

createrepo() {
    dir=$1
    name=$(basename $dir)
    echo ""
    echo "Cloning remote to ${dir}"
    rm -rf "${dir}"
    mkdir -p "${dir}"
    (cd "${dir}" && git clone --origin origin "file://${remotedir}" .)
    (cd "${dir}" && git config --local user.name ${name})
    (cd "${dir}" && git config --local user.email ${name}@example.com)
}

tmpdir=$1
localdir="${tmpdir}/local"
remotedir="${tmpdir}/remote"
notgit="${tmpdir}/notgit"

# create base dir
echo ""
echo "Creating temporary test assets in ${tmpdir}"
mkdir -p ${tmpdir}

# create remote repo
echo ""
echo "Creating remote repository ${remotedir}"
rm -rf "${remotedir}"
mkdir -p "${remotedir}"
(cd "${remotedir}" && git --bare init --initial-branch=master)

# create first local repo
createrepo "${localdir}"

# populate an initial import
echo "Populating and pushing"
(cd "${localdir}" && echo "test" >test.txt && mkdir subdir && echo "subdir" >subdir/subdir.txt)
(cd "${localdir}" && git checkout -b master && git add . && git commit -m "initial import" && git push --set-upstream --all origin)

# create more local repos
for name in localother alice bob
do
    createrepo "${tmpdir}/${name}"
done

# create a non-git area
mkdir -p "${localdir}" "${notgit}"

echo "Done."
