#!/bin/bash
set -e

echo "Creating test assets..."
tmpdir="/tmp/mob"
localdir="${tmpdir}/local"
remotedir="${tmpdir}/remote"
echo ""
echo "Root of temporary test assets: ${tmpdir}"
echo "Path to central repository ('remote'): ${remotedir}"
echo "Path to clone of central repository ('local'): ${localdir}"

mkdir -p "${localdir}" "${remotedir}"
rm -rf "${localdir}" "${remotedir}"
mkdir -p "${localdir}" "${remotedir}"

echo ""
echo "Creating test repositories..."
(cd "${remotedir}" && git --bare init)
(cd "${localdir}" && git clone --origin origin "file://${remotedir}" . && echo "test" >test.txt && git add . && git commit -m "initial import" && git push --set-upstream --all origin)

# optional
echo ""
echo "Creating a second mob participant's repository..."
localotherdir="${tmpdir}/localother"
echo "Path to second clone of central repository ('localotherdir'): ${localotherdir}"
rm -rf "${localotherdir}"
mkdir -p "${localotherdir}"
(cd "${localotherdir}" && git clone --origin origin "file://${remotedir}" .)

echo "Done."
