#!/bin/bash
set -e

cleanrepo() {
    dir=$1
    echo ""
    echo "cleanrepo: Delete ${dir}"
    rm -rf "${dir}"
}

createremoterepo() {
    dir=$1
    echo ""
    echo "createremoterepo: Creating remote repository ${dir}"
    mkdir -p "${dir}"
    (cd "${dir}" && git --bare init && git symbolic-ref HEAD "refs/heads/${branch}")
}

clonerepo() {
    dir=$1
    echo ""
    echo "clonerepo: Cloning remote ${remotedir} to ${dir}"
    name=$(basename "${dir}")
    mkdir -p "${dir}"
    (cd "${dir}" && git clone --origin origin "file://${remotedir}" .)
    (cd "${dir}" && git config --local user.name "${name}")
    (cd "${dir}" && git config --local user.email "${name}@example.com")
}

clonerepowithsymlink() {
  dir="$1"
  gitdir="$2"
  clonerepo "${dir}"
  echo ""
  echo "clonerepowithsymlink: move .git to ${gitdir} and create symlink to it"
  mv "${dir}/.git" "$2"
  ln -s "${gitdir}" "${dir}/.git"
}

cleanrepowithsymlink() {
  dir="$1"
  gitdir="$2"
  echo ""
  echo "cleanrepowithsymlink: Delete ${dir} and ${gitdir}"
  rm -rf "${dir}" "${gitdir}"
}

tmpdir=$1
localdir="${tmpdir}/local"
remotedir="${tmpdir}/remote"
notgit="${tmpdir}/notgit"

branch=master # fixed to master for now


# create base dir
echo ""
echo "Creating temporary test assets in ${tmpdir}"
mkdir -p "${tmpdir}"

echo "create remote repo"
cleanrepo "${remotedir}"
createremoterepo "${remotedir}"

echo "create first local repo"
cleanrepo "${localdir}"
clonerepo "${localdir}"

echo "Populating and initial import pushing"
(cd "${localdir}" && echo "test" >test.txt && mkdir -p subdir && echo "subdir" >subdir/subdir.txt)
(cd "${localdir}" && git checkout -b "${branch}" && git add . && git commit --message "initial import" && git push --set-upstream --all origin)


echo "Creating more local repos"
for name in localother alice bob
do
    cleanrepo "${tmpdir}/${name}"
    clonerepo "${tmpdir}/${name}"
    echo "Created local repo ${name}"
done


echo "Creating non-git dirs"
for dir in "${localdir}" "${notgit}"
do
    mkdir -p "${dir}"
    echo "Created non-git dir ${dir}"
done

echo "Creating local repo with .git symlink"
localsymlink="${tmpdir}/local-symlink"
localsymlink_gitdir="${tmpdir}/local-symlink.git"
cleanrepowithsymlink "${localsymlink}" "${localsymlink_gitdir}"
clonerepowithsymlink "${localsymlink}" "${localsymlink_gitdir}"

echo "Done."
